# Pattern definitions for information extraction
emails: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
phones: '\b(\+?\d{1,3}[-.\s]?)?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}\b'
names: '\b(?:Mr\.|Mrs\.|Ms\.|Dr\.)?\s*[A-Z][a-z]+\s+[A-Z][a-z]+\b'
ip_addresses: '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b'
api_keys: '\b(?:api|key|token|secret)[_\-]?key\s*[:=]\s*[\'"]?([a-f0-9]{32,})[\'"]?\b'
important_paths: '\b(admin|backup|config|secret|internal|dashboard)\b'
juicy_files: '\.(bak|old|sql|backup|conf|config|env|swp)\b'