phone_numbers: '\b\d{3}[-.\s]?\d{3}[-.\s]?\d{4}\b'
names: '\b(?:Mr\.|Mrs\.|Ms\.|Dr\.)?\s*[A-Z][a-z]+\s+[A-Z][a-z]+\b'
ip_addresses: '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b'
important_paths: '/(admin|backup|config|secret|internal|dashboard)/'
juicy_files: '\.(bak|old|sql|backup|conf|config|env|swp)\b'