passive:
  - name: subfinder
    command: "subfinder -d {target} -silent -t 50"
    timeout: 300

active:
  - name: httpx
    command: "$HOME/go/bin/httpx -l {target} -title -status-code -timeout 5"
    timeout: 200
    resources:
      max_cpu: 80
      max_mem: 1000